# -*- coding: utf-8 -*-
"""dusung_project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XWKGQdTp8Y9wUaiETmU-JSOg2_0adMnn
"""
# 막대 그래프
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files
files.upload()
df = pd.read_csv('Youtuber.csv')
country_counts = df['Country'].value_counts()
plt.figure(figsize = (12, 6))
country_counts.plot(kind = 'bar', color = 'skyblue')
plt.title('Count of Channels by Country')
plt.xlabel('Country')
plt.ylabel('Number of Channels')
plt.show()
# 원 그래프
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files
files.upload()
df = pd.read_csv('Youtuber.csv')
category_counts = df['Country'].value_counts()
plt.figure(figsize = (12, 6))
plt.pie(category_counts, labels = category_counts.index, autopct = '%1.1f%%', startangle = 90)
plt.title('Distribution of Channels by Country')
plt.show()
# 가로 막대 그래프
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files
files.upload()
df = pd.read_csv('Youtuber.csv')
country_counts = df['Country'].value_counts()
plt.figure(figsize = (12, 6))
country_counts.plot(kind = 'barh', color = 'yellow')
plt.title('Count of Channels by Country')
plt.xlabel('Number of Channels')
plt.ylabel('Country')
plt.show()